import { IItem } from '../types';

export const FORM_INITIAL_STATE: IItem[] = [
  {
    key: '1',
    title: 'Use Hooks in a React application (Default TODO from INITIAL_STATE.js)',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    dataIndex: 0,
  },
  {
    key: '2',
    title: 'Сменить вывод звук',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 2,
  },
  {
    key: '3',
    title: 'Закончить уборку',
    date: new Date('2021-01-01').toISOString().slice(0, 10),
    completed: false,
    dataIndex: 0,
  },
  {
    key: '4',
    title: 'Сделать задачи помобильному',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 4,
  },
  {
    key: '5',
    title: 'Помыться',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    dataIndex: 5,
  },
  {
    key: '6',
    title: 'Приготовить обед',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 6,
  },
  {
    key: '7',
    title: 'Покормить Нокса',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    dataIndex: 7,
  },
  {
    key: '8',
    title: 'Посмотреть фильм очень и очень интересный',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 8,
  },
  {
    key: '9',
    title: 'Загрузить посуду в посудомойку',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 9,
  },
  {
    key: '10',
    title: 'Подготовитсья к работе ',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 10,
  },
  {
    key: '11',
    title: 'Ещё 1 варианта задачи. Надоело придумывать',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 11,
  },
  {
    key: '12',
    title: 'ну и последняя, для прокрутки',
    date: new Date().toISOString().slice(0, 10),
    completed: true,
    dataIndex: 12,
  },
  {
    key: '13',
    title: 'ладно, ещё одна',
    date: new Date('2021-01-01').toISOString().slice(0, 10),
    completed: false,
    dataIndex: 13,
  },
];
